from __future__ import annotations

import os
import re
import tempfile
from pathlib import Path
from typing import Mapping


class EnvFileError(ValueError):
    pass


_ENV_KEY = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")


def load_env_file(
    path: str | Path,
    *,
    override: bool = True,
) -> dict[str, str]:
    env_path = Path(path).expanduser().resolve()
    if not env_path.is_file():
        raise EnvFileError(f"configuration file does not exist: {env_path}")
    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(
        env_path.read_text(encoding="utf-8").splitlines(),
        start=1,
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            raise EnvFileError(f"invalid configuration at line {line_number}")
        key, value = line.split("=", 1)
        key = key.strip()
        if not _ENV_KEY.fullmatch(key):
            raise EnvFileError(f"invalid environment key at line {line_number}")
        values[key] = value
    for key, value in values.items():
        if override or key not in os.environ:
            os.environ[key] = value
    return values


def write_env_file(path: str | Path, values: Mapping[str, object]) -> Path:
    env_path = Path(path).expanduser().resolve()
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by Kitty setup. Keep this file secret."]
    for key, raw_value in values.items():
        if not _ENV_KEY.fullmatch(key):
            raise EnvFileError(f"invalid environment key: {key}")
        value = str(raw_value)
        if "\n" in value or "\r" in value or "\x00" in value:
            raise EnvFileError(f"configuration value for {key} contains a newline")
        lines.append(f"{key}={value}")
    content = "\n".join(lines) + "\n"

    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{env_path.name}.",
        dir=env_path.parent,
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.replace(env_path)
        env_path.chmod(0o600)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
    return env_path
